# Generated by Django 5.0.4 on 2024-04-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='registration_ip',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP de Cadastro'),
        ),
    ]
