# Generated by Django 5.0.4 on 2024-04-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_professores/%Y/%m/%d/', verbose_name='Foto')),
                ('data_de_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ip_de_cadastro', models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP de Cadastro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Equipe')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superusuário')),
                ('groups', models.ManyToManyField(blank=True, help_text='Os grupos aos quais este usuário pertence. Um grupo representa uma coleção de permissões.', related_name='grupos_professor', to='auth.group', verbose_name='Grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permissões específicas para este usuário.', related_name='permissoes_usuario_professor', to='auth.permission', verbose_name='Permissões de Usuário')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
    ]
